baseURL: https://www.hugobricks.preview.usecue.com
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
  fr:
    languageName: French
    contentDir: Content/fr
    weight: 2
    disabled: false