baseURL: https://www.hugobricks.preview.usecue.com
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
    permalinks:
      page:
        posts: /blog/:slug
        services: /services/:slug
      section:
        posts: /blog/
        services: /services/
  nl:
    languageName: Nederlands
    contentDir: content/nl
    weight: 2
    disabled: false
    permalinks:
      page:
        posts: /blog/:slug
        services: /diensten/:slug
      section:
        posts: /blog/
        services: /diensten/